-- Fantasy Chatroom 2026-27 roster seed, generated from ESPN roster pages
-- Safe to re-run: managers use WHERE NOT EXISTS guards, teams use ON CONFLICT,
-- roster_entries are cleared and reinserted per team.

-- 1. Season row
insert into seasons (year, season_number)
select 2026, 12
where not exists (select 1 from seasons where year = 2026);

-- 2. Managers (no-op if these names already exist -- they should, since
-- schedule.js, matchups, and every other page already reference them)
insert into managers (name, slug)
select v.name, v.slug from (values
  ('Wally', 'wally'),
  ('Caden', 'caden'),
  ('Dan', 'dan'),
  ('Big E', 'big-e'),
  ('Freed', 'freed'),
  ('John', 'john'),
  ('Reid', 'reid'),
  ('JM', 'jm'),
  ('Braden', 'braden'),
  ('Mamby/Tenner', 'mamby-tenner')
) as v(name, slug)
where not exists (select 1 from managers m where m.name = v.name);

-- 3. Teams for season 2026 (team_name updates if the team row already exists)
insert into teams (season_id, manager_id, team_name)
select s.id, m.id, v.team_name
from (values
  ('Wally', 'Team Wal'),
  ('Caden', 'Greg''s Gang'),
  ('Dan', 'The Dans'),
  ('Big E', 'Run achane on her'),
  ('Freed', 'Josh Allens'),
  ('John', 'Team Ittounas'),
  ('Reid', 'Bo Picks'),
  ('JM', 'UNITED FRONT'),
  ('Braden', 'Kittle and Friends'),
  ('Mamby/Tenner', 'Team Tenner n Mamby')
) as v(manager_name, team_name)
join managers m on m.name = v.manager_name
cross join (select id from seasons where year = 2026) s
on conflict (season_id, manager_id) do update set team_name = excluded.team_name;

-- 4. Players (no-op if a player with this exact name already exists)
insert into players (name, position)
select v.name, v.position from (values
  ('A.J. Brown', 'WR'),
  ('Aaron Jones Sr.', 'RB'),
  ('Alec Pierce', 'WR'),
  ('Alvin Kamara', 'RB'),
  ('Amon-Ra St. Brown', 'WR'),
  ('Ashton Jeanty', 'RB'),
  ('Bhayshul Tuten', 'RB'),
  ('Bijan Robinson', 'RB'),
  ('Blake Corum', 'RB'),
  ('Brandon Aubrey', 'K'),
  ('Breece Hall', 'RB'),
  ('Brian Robinson Jr.', 'RB'),
  ('Brian Thomas Jr.', 'WR'),
  ('Brock Bowers', 'TE'),
  ('Brock Purdy', 'QB'),
  ('Bucky Irving', 'RB'),
  ('Caleb Douglas', 'WR'),
  ('Caleb Williams', 'QB'),
  ('Cam Little', 'K'),
  ('Cam Skattebo', 'RB'),
  ('Cameron Dicker', 'K'),
  ('Carnell Tate', 'WR'),
  ('CeeDee Lamb', 'WR'),
  ('Chase Brown', 'RB'),
  ('Chig Okonkwo', 'TE'),
  ('Chris Bell', 'WR'),
  ('Chris Godwin Jr.', 'WR'),
  ('Chris Olave', 'WR'),
  ('Chris Rodriguez Jr.', 'RB'),
  ('Christian McCaffrey', 'RB'),
  ('Christian Watson', 'WR'),
  ('Chuba Hubbard', 'RB'),
  ('Colston Loveland', 'TE'),
  ('Courtland Sutton', 'WR'),
  ('D''Andre Swift', 'RB'),
  ('DJ Moore', 'WR'),
  ('DK Metcalf', 'WR'),
  ('Dak Prescott', 'QB'),
  ('Dallas Goedert', 'TE'),
  ('Dalton Kincaid', 'TE'),
  ('Davante Adams', 'WR'),
  ('David Montgomery', 'RB'),
  ('De''Von Achane', 'RB'),
  ('De''Zhaun Stribling', 'WR'),
  ('DeVonta Smith', 'WR'),
  ('Deebo Samuel Sr.', 'WR'),
  ('Derrick Henry', 'RB'),
  ('Drake London', 'WR'),
  ('Drake Maye', 'QB'),
  ('Eddy Pineiro', 'K'),
  ('Emeka Egbuka', 'WR'),
  ('Emmett Johnson', 'RB'),
  ('Garrett Wilson', 'WR'),
  ('George Kittle', 'TE'),
  ('George Pickens', 'WR'),
  ('Harold Fannin Jr.', 'TE'),
  ('Harrison Butker', 'K'),
  ('Harrison Mevis', 'K'),
  ('Isaiah Likely', 'TE'),
  ('J.K. Dobbins', 'RB'),
  ('Ja''Kobi Lane', 'WR'),
  ('Ja''Marr Chase', 'WR'),
  ('Jacory Croskey-Merritt', 'RB'),
  ('Jadarian Price', 'RB'),
  ('Jahmyr Gibbs', 'RB'),
  ('Jake Bates', 'K'),
  ('Jake Ferguson', 'TE'),
  ('Jakobi Meyers', 'WR'),
  ('Jalen Hurts', 'QB'),
  ('James Cook III', 'RB'),
  ('Jameson Williams', 'WR'),
  ('Jason Myers', 'K'),
  ('Javonte Williams', 'RB'),
  ('Jaxon Smith-Njigba', 'WR'),
  ('Jaxson Dart', 'QB'),
  ('Jayden Daniels', 'QB'),
  ('Jayden Reed', 'WR'),
  ('Jaylen Waddle', 'WR'),
  ('Jaylen Warren', 'RB'),
  ('Jeremiyah Love', 'RB'),
  ('Joe Burrow', 'QB'),
  ('Jonah Coleman', 'RB'),
  ('Jonathan Taylor', 'RB'),
  ('Jonathon Brooks', 'RB'),
  ('Jordan Addison', 'WR'),
  ('Jordan Mason', 'RB'),
  ('Jordyn Tyson', 'WR'),
  ('Josh Allen', 'QB'),
  ('Josh Downs', 'WR'),
  ('Josh Jacobs', 'RB'),
  ('Justin Herbert', 'QB'),
  ('Justin Jefferson', 'WR'),
  ('Juwan Johnson', 'TE'),
  ('KC Concepcion', 'WR'),
  ('Ka''imi Fairbairn', 'K'),
  ('Kaelon Black', 'RB'),
  ('Kenneth Walker III', 'RB'),
  ('Kenny Gainwell', 'RB'),
  ('Kimani Vidal', 'RB'),
  ('Kyle Monangai', 'RB'),
  ('Kyle Pitts Sr.', 'TE'),
  ('Kyler Murray', 'QB'),
  ('Kyren Williams', 'RB'),
  ('Ladd McConkey', 'WR'),
  ('Lamar Jackson', 'QB'),
  ('Luther Burden III', 'WR'),
  ('Makai Lemon', 'WR'),
  ('Malik Davis', 'RB'),
  ('Malik Nabers', 'WR'),
  ('Malik Washington', 'WR'),
  ('Malik Willis', 'QB'),
  ('MarShawn Lloyd', 'RB'),
  ('Mark Andrews', 'TE'),
  ('Marvin Harrison Jr.', 'WR'),
  ('Matthew Golden', 'WR'),
  ('Matthew Stafford', 'QB'),
  ('Michael Pittman Jr.', 'WR'),
  ('Michael Wilson', 'WR'),
  ('Mike Evans', 'WR'),
  ('Mike Washington Jr.', 'RB'),
  ('Nico Collins', 'WR'),
  ('Omarion Hampton', 'RB'),
  ('Parker Washington', 'WR'),
  ('Patrick Mahomes', 'QB'),
  ('Puka Nacua', 'WR'),
  ('Quentin Johnston', 'WR'),
  ('Quinshon Judkins', 'RB'),
  ('RJ Harvey', 'RB'),
  ('Rachaad White', 'RB'),
  ('Rashee Rice', 'WR'),
  ('Ray Davis', 'RB'),
  ('Rhamondre Stevenson', 'RB'),
  ('Rico Dowdle', 'RB'),
  ('Rome Odunze', 'WR'),
  ('Romeo Doubs', 'WR'),
  ('Sam LaPorta', 'TE'),
  ('Saquon Barkley', 'RB'),
  ('Stefon Diggs', 'WR'),
  ('Tank Bigsby', 'RB'),
  ('Tee Higgins', 'WR'),
  ('Terry McLaurin', 'WR'),
  ('Tetairoa McMillan', 'WR'),
  ('Tony Pollard', 'RB'),
  ('Travis Etienne Jr.', 'RB'),
  ('Travis Kelce', 'TE'),
  ('TreVeyon Henderson', 'RB'),
  ('Trevor Lawrence', 'QB'),
  ('Trey McBride', 'TE'),
  ('Tucker Kraft', 'TE'),
  ('Tyjae Spears', 'RB'),
  ('Tyler Allgeier', 'RB'),
  ('Tyler Shough', 'QB'),
  ('Tyler Warren', 'TE'),
  ('Wan''Dale Robinson', 'WR'),
  ('Will Reichard', 'K'),
  ('Woody Marks', 'RB'),
  ('Xavier Worthy', 'WR'),
  ('Zach Charbonnet', 'RB'),
  ('Zay Flowers', 'WR')
) as v(name, position)
where not exists (select 1 from players p where p.name = v.name);

-- 5. Clear and reinsert this season's roster_entries for these 10 teams
delete from roster_entries where team_id in (
  select t.id from teams t
  join seasons s on s.id = t.season_id and s.year = 2026
  join managers m on m.id = t.manager_id
  where m.name in ('Wally', 'Caden', 'Dan', 'Big E', 'Freed', 'John', 'Reid', 'JM', 'Braden', 'Mamby/Tenner')
);

insert into roster_entries (player_id, team_id)
select p.id, t.id
from (values
  ('Wally', 'Caleb Williams'),
  ('Wally', 'Omarion Hampton'),
  ('Wally', 'Chase Brown'),
  ('Wally', 'DeVonta Smith'),
  ('Wally', 'Malik Nabers'),
  ('Wally', 'Tucker Kraft'),
  ('Wally', 'Jadarian Price'),
  ('Wally', 'MarShawn Lloyd'),
  ('Wally', 'Cam Little'),
  ('Wally', 'Jameson Williams'),
  ('Wally', 'De''Zhaun Stribling'),
  ('Wally', 'Kaelon Black'),
  ('Wally', 'Kimani Vidal'),
  ('Wally', 'Kyler Murray'),
  ('Wally', 'Chig Okonkwo'),
  ('Wally', 'Jordyn Tyson'),
  ('Caden', 'Josh Allen'),
  ('Caden', 'Ashton Jeanty'),
  ('Caden', 'Bucky Irving'),
  ('Caden', 'Ja''Marr Chase'),
  ('Caden', 'Chris Olave'),
  ('Caden', 'Harold Fannin Jr.'),
  ('Caden', 'Terry McLaurin'),
  ('Caden', 'Rhamondre Stevenson'),
  ('Caden', 'Will Reichard'),
  ('Caden', 'Michael Wilson'),
  ('Caden', 'Jordan Mason'),
  ('Caden', 'Jakobi Meyers'),
  ('Caden', 'Tyler Allgeier'),
  ('Caden', 'Mike Washington Jr.'),
  ('Caden', 'Malik Washington'),
  ('Caden', 'Ja''Kobi Lane'),
  ('Dan', 'Lamar Jackson'),
  ('Dan', 'Kenneth Walker III'),
  ('Dan', 'Javonte Williams'),
  ('Dan', 'Amon-Ra St. Brown'),
  ('Dan', 'Luther Burden III'),
  ('Dan', 'Colston Loveland'),
  ('Dan', 'TreVeyon Henderson'),
  ('Dan', 'Alec Pierce'),
  ('Dan', 'Brandon Aubrey'),
  ('Dan', 'Matthew Golden'),
  ('Dan', 'Michael Pittman Jr.'),
  ('Dan', 'Dak Prescott'),
  ('Dan', 'Caleb Douglas'),
  ('Dan', 'Emmett Johnson'),
  ('Dan', 'Juwan Johnson'),
  ('Dan', 'Malik Davis'),
  ('Big E', 'Trevor Lawrence'),
  ('Big E', 'Jonathan Taylor'),
  ('Big E', 'De''Von Achane'),
  ('Big E', 'George Pickens'),
  ('Big E', 'Emeka Egbuka'),
  ('Big E', 'Travis Kelce'),
  ('Big E', 'Davante Adams'),
  ('Big E', 'Rome Odunze'),
  ('Big E', 'Harrison Butker'),
  ('Big E', 'Parker Washington'),
  ('Big E', 'Rico Dowdle'),
  ('Big E', 'Chuba Hubbard'),
  ('Big E', 'Isaiah Likely'),
  ('Big E', 'Quentin Johnston'),
  ('Big E', 'Jonah Coleman'),
  ('Big E', 'Zach Charbonnet'),
  ('Freed', 'Justin Herbert'),
  ('Freed', 'Derrick Henry'),
  ('Freed', 'Bhayshul Tuten'),
  ('Freed', 'Puka Nacua'),
  ('Freed', 'Jaylen Waddle'),
  ('Freed', 'Brock Bowers'),
  ('Freed', 'Mike Evans'),
  ('Freed', 'Christian Watson'),
  ('Freed', 'Harrison Mevis'),
  ('Freed', 'Jaylen Warren'),
  ('Freed', 'Brian Thomas Jr.'),
  ('Freed', 'Jacory Croskey-Merritt'),
  ('Freed', 'Blake Corum'),
  ('Freed', 'KC Concepcion'),
  ('Freed', 'Tank Bigsby'),
  ('Freed', 'Matthew Stafford'),
  ('John', 'Jalen Hurts'),
  ('John', 'James Cook III'),
  ('John', 'Breece Hall'),
  ('John', 'CeeDee Lamb'),
  ('John', 'DJ Moore'),
  ('John', 'Trey McBride'),
  ('John', 'David Montgomery'),
  ('John', 'DK Metcalf'),
  ('John', 'Jason Myers'),
  ('John', 'Jordan Addison'),
  ('John', 'Kyle Monangai'),
  ('John', 'Rachaad White'),
  ('John', 'Deebo Samuel Sr.'),
  ('John', 'Romeo Doubs'),
  ('John', 'Woody Marks'),
  ('John', 'Ray Davis'),
  ('Reid', 'Jayden Daniels'),
  ('Reid', 'Saquon Barkley'),
  ('Reid', 'Travis Etienne Jr.'),
  ('Reid', 'Jaxon Smith-Njigba'),
  ('Reid', 'Rashee Rice'),
  ('Reid', 'Sam LaPorta'),
  ('Reid', 'Ladd McConkey'),
  ('Reid', 'Tee Higgins'),
  ('Reid', 'Cameron Dicker'),
  ('Reid', 'Jonathon Brooks'),
  ('Reid', 'J.K. Dobbins'),
  ('Reid', 'Wan''Dale Robinson'),
  ('Reid', 'Dallas Goedert'),
  ('Reid', 'Patrick Mahomes'),
  ('Reid', 'Tyjae Spears'),
  ('Reid', 'Chris Bell'),
  ('JM', 'Jaxson Dart'),
  ('JM', 'Jahmyr Gibbs'),
  ('JM', 'Jeremiyah Love'),
  ('JM', 'Drake London'),
  ('JM', 'Carnell Tate'),
  ('JM', 'Jake Ferguson'),
  ('JM', 'Cam Skattebo'),
  ('JM', 'Quinshon Judkins'),
  ('JM', 'Eddy Pineiro'),
  ('JM', 'Marvin Harrison Jr.'),
  ('JM', 'Josh Jacobs'),
  ('JM', 'Chris Godwin Jr.'),
  ('JM', 'Makai Lemon'),
  ('JM', 'Brock Purdy'),
  ('JM', 'Malik Willis'),
  ('JM', 'Dalton Kincaid'),
  ('Braden', 'Joe Burrow'),
  ('Braden', 'Christian McCaffrey'),
  ('Braden', 'Kyren Williams'),
  ('Braden', 'Justin Jefferson'),
  ('Braden', 'Zay Flowers'),
  ('Braden', 'Tyler Warren'),
  ('Braden', 'Tetairoa McMillan'),
  ('Braden', 'George Kittle'),
  ('Braden', 'Jake Bates'),
  ('Braden', 'Jayden Reed'),
  ('Braden', 'Kenny Gainwell'),
  ('Braden', 'Josh Downs'),
  ('Braden', 'Chris Rodriguez Jr.'),
  ('Braden', 'Xavier Worthy'),
  ('Braden', 'Tyler Shough'),
  ('Braden', 'Alvin Kamara'),
  ('Mamby/Tenner', 'Drake Maye'),
  ('Mamby/Tenner', 'Bijan Robinson'),
  ('Mamby/Tenner', 'D''Andre Swift'),
  ('Mamby/Tenner', 'A.J. Brown'),
  ('Mamby/Tenner', 'Nico Collins'),
  ('Mamby/Tenner', 'Kyle Pitts Sr.'),
  ('Mamby/Tenner', 'Garrett Wilson'),
  ('Mamby/Tenner', 'Courtland Sutton'),
  ('Mamby/Tenner', 'Ka''imi Fairbairn'),
  ('Mamby/Tenner', 'Tony Pollard'),
  ('Mamby/Tenner', 'Stefon Diggs'),
  ('Mamby/Tenner', 'Aaron Jones Sr.'),
  ('Mamby/Tenner', 'RJ Harvey'),
  ('Mamby/Tenner', 'Mark Andrews'),
  ('Mamby/Tenner', 'Brian Robinson Jr.')
) as v(manager_name, player_name)
join managers m on m.name = v.manager_name
join teams t on t.manager_id = m.id
join seasons s on s.id = t.season_id and s.year = 2026
join players p on p.name = v.player_name;
