-- Fantasy Chatroom 2026-27 Week 1 per-player projections, from ESPN roster pages.
-- Stored as roster_entries.stats->'proj'->'1' so lib/predictions.js's
-- projectedWeekScore() can build real Week 1 forward lines instead of
-- treating Week 1 as a coin flip. Safe to re-run.
--
-- Builds the nested {proj: {1: ...}} object with || merges rather than
-- jsonb_set(), since jsonb_set only creates the *last* segment of a path
-- when missing -- with existing stats of '{}' (no 'proj' key at all) it
-- silently no-ops on a multi-level path like '{proj,1}' instead of erroring.

with proj_data (manager_name, player_name, proj) as (
  values
    ('Wally', 'Caleb Williams', 17.0),
    ('Wally', 'Omarion Hampton', 18.8),
    ('Wally', 'Chase Brown', 16.6),
    ('Wally', 'DeVonta Smith', 13.7),
    ('Wally', 'Malik Nabers', 12.9),
    ('Wally', 'Tucker Kraft', 8.3),
    ('Wally', 'Jadarian Price', 15.1),
    ('Wally', 'MarShawn Lloyd', 14.1),
    ('Wally', 'Cam Little', 9.3),
    ('Wally', 'Jameson Williams', 11.7),
    ('Wally', 'De''Zhaun Stribling', 9.0),
    ('Wally', 'Kaelon Black', 3.4),
    ('Wally', 'Kimani Vidal', 2.6),
    ('Wally', 'Kyler Murray', 17.2),
    ('Wally', 'Chig Okonkwo', 6.1),
    ('Wally', 'Jordyn Tyson', 0.0),
    ('Caden', 'Josh Allen', 20.3),
    ('Caden', 'Ashton Jeanty', 19.2),
    ('Caden', 'Bucky Irving', 13.4),
    ('Caden', 'Ja''Marr Chase', 18.7),
    ('Caden', 'Chris Olave', 13.6),
    ('Caden', 'Harold Fannin Jr.', 10.0),
    ('Caden', 'Terry McLaurin', 11.4),
    ('Caden', 'Rhamondre Stevenson', 10.9),
    ('Caden', 'Will Reichard', 8.9),
    ('Caden', 'Michael Wilson', 9.5),
    ('Caden', 'Jordan Mason', 9.9),
    ('Caden', 'Jakobi Meyers', 9.7),
    ('Caden', 'Tyler Allgeier', 7.2),
    ('Caden', 'Mike Washington Jr.', 7.5),
    ('Caden', 'Malik Washington', 9.5),
    ('Caden', 'Ja''Kobi Lane', 6.2),
    ('Dan', 'Lamar Jackson', 20.2),
    ('Dan', 'Kenneth Walker III', 15.7),
    ('Dan', 'Javonte Williams', 16.6),
    ('Dan', 'Amon-Ra St. Brown', 17.5),
    ('Dan', 'Luther Burden III', 11.2),
    ('Dan', 'Colston Loveland', 11.0),
    ('Dan', 'TreVeyon Henderson', 10.6),
    ('Dan', 'Alec Pierce', 9.2),
    ('Dan', 'Brandon Aubrey', 10.4),
    ('Dan', 'Matthew Golden', 10.4),
    ('Dan', 'Michael Pittman Jr.', 11.1),
    ('Dan', 'Dak Prescott', 17.1),
    ('Dan', 'Caleb Douglas', 6.3),
    ('Dan', 'Emmett Johnson', 3.1),
    ('Dan', 'Juwan Johnson', 7.8),
    ('Dan', 'Malik Davis', 3.7),
    ('Big E', 'Trevor Lawrence', 17.6),
    ('Big E', 'Jonathan Taylor', 19.2),
    ('Big E', 'De''Von Achane', 19.3),
    ('Big E', 'George Pickens', 13.8),
    ('Big E', 'Emeka Egbuka', 13.5),
    ('Big E', 'Travis Kelce', 8.8),
    ('Big E', 'Davante Adams', 13.2),
    ('Big E', 'Rome Odunze', 12.0),
    ('Big E', 'Harrison Butker', 9.0),
    ('Big E', 'Parker Washington', 10.2),
    ('Big E', 'Rico Dowdle', 13.8),
    ('Big E', 'Chuba Hubbard', 12.1),
    ('Big E', 'Isaiah Likely', 8.5),
    ('Big E', 'Quentin Johnston', 9.9),
    ('Big E', 'Jonah Coleman', 4.3),
    ('Big E', 'Zach Charbonnet', 0.0),
    ('Freed', 'Justin Herbert', 19.7),
    ('Freed', 'Derrick Henry', 18.4),
    ('Freed', 'Bhayshul Tuten', 15.0),
    ('Freed', 'Puka Nacua', 19.8),
    ('Freed', 'Jaylen Waddle', 11.4),
    ('Freed', 'Brock Bowers', 14.3),
    ('Freed', 'Mike Evans', 10.0),
    ('Freed', 'Christian Watson', 10.6),
    ('Freed', 'Harrison Mevis', 9.8),
    ('Freed', 'Jaylen Warren', 13.3),
    ('Freed', 'Brian Thomas Jr.', 9.7),
    ('Freed', 'Jacory Croskey-Merritt', 9.3),
    ('Freed', 'Blake Corum', 10.4),
    ('Freed', 'KC Concepcion', 8.4),
    ('Freed', 'Tank Bigsby', 4.9),
    ('Freed', 'Matthew Stafford', 17.7),
    ('John', 'Jalen Hurts', 22.0),
    ('John', 'James Cook III', 16.3),
    ('John', 'Breece Hall', 17.6),
    ('John', 'CeeDee Lamb', 16.1),
    ('John', 'DJ Moore', 11.0),
    ('John', 'Trey McBride', 12.7),
    ('John', 'David Montgomery', 13.8),
    ('John', 'DK Metcalf', 11.6),
    ('John', 'Jason Myers', 9.9),
    ('John', 'Jordan Addison', 9.3),
    ('John', 'Kyle Monangai', 11.2),
    ('John', 'Rachaad White', 9.0),
    ('John', 'Deebo Samuel Sr.', 10.4),
    ('John', 'Romeo Doubs', 7.6),
    ('John', 'Woody Marks', 9.9),
    ('John', 'Ray Davis', 5.2),
    ('Reid', 'Jayden Daniels', 17.8),
    ('Reid', 'Saquon Barkley', 19.2),
    ('Reid', 'Travis Etienne Jr.', 15.9),
    ('Reid', 'Jaxon Smith-Njigba', 17.7),
    ('Reid', 'Rashee Rice', 13.4),
    ('Reid', 'Sam LaPorta', 9.9),
    ('Reid', 'Ladd McConkey', 12.9),
    ('Reid', 'Tee Higgins', 12.2),
    ('Reid', 'Cameron Dicker', 10.8),
    ('Reid', 'Jonathon Brooks', 12.2),
    ('Reid', 'J.K. Dobbins', 10.5),
    ('Reid', 'Wan''Dale Robinson', 9.4),
    ('Reid', 'Dallas Goedert', 10.0),
    ('Reid', 'Patrick Mahomes', 16.0),
    ('Reid', 'Tyjae Spears', 9.3),
    ('Reid', 'Chris Bell', 4.9),
    ('JM/Cameron', 'Jaxson Dart', 19.5),
    ('JM/Cameron', 'Jahmyr Gibbs', 22.9),
    ('JM/Cameron', 'Jeremiyah Love', 15.1),
    ('JM/Cameron', 'Drake London', 13.8),
    ('JM/Cameron', 'Carnell Tate', 11.2),
    ('JM/Cameron', 'Jake Ferguson', 8.7),
    ('JM/Cameron', 'Cam Skattebo', 14.5),
    ('JM/Cameron', 'Quinshon Judkins', 14.6),
    ('JM/Cameron', 'Eddy Pineiro', 9.2),
    ('JM/Cameron', 'Marvin Harrison Jr.', 10.7),
    ('JM/Cameron', 'Josh Jacobs', 0.0),
    ('JM/Cameron', 'Chris Godwin Jr.', 8.8),
    ('JM/Cameron', 'Makai Lemon', 9.0),
    ('JM/Cameron', 'Brock Purdy', 16.0),
    ('JM/Cameron', 'Malik Willis', 16.0),
    ('JM/Cameron', 'Dalton Kincaid', 7.9),
    ('Braden', 'Joe Burrow', 18.5),
    ('Braden', 'Christian McCaffrey', 18.7),
    ('Braden', 'Kyren Williams', 14.8),
    ('Braden', 'Justin Jefferson', 15.9),
    ('Braden', 'Zay Flowers', 13.5),
    ('Braden', 'Tyler Warren', 11.2),
    ('Braden', 'Tetairoa McMillan', 13.9),
    ('Braden', 'George Kittle', 7.5),
    ('Braden', 'Jake Bates', 9.1),
    ('Braden', 'Jayden Reed', 9.5),
    ('Braden', 'Kenny Gainwell', 10.7),
    ('Braden', 'Josh Downs', 8.2),
    ('Braden', 'Chris Rodriguez Jr.', 5.5),
    ('Braden', 'Xavier Worthy', 9.1),
    ('Braden', 'Tyler Shough', 14.8),
    ('Braden', 'Alvin Kamara', 0.0),
    ('Mamby/Tenner', 'Drake Maye', 17.0),
    ('Mamby/Tenner', 'Bijan Robinson', 20.1),
    ('Mamby/Tenner', 'D''Andre Swift', 13.4),
    ('Mamby/Tenner', 'A.J. Brown', 13.3),
    ('Mamby/Tenner', 'Nico Collins', 14.7),
    ('Mamby/Tenner', 'Kyle Pitts Sr.', 9.2),
    ('Mamby/Tenner', 'Garrett Wilson', 13.6),
    ('Mamby/Tenner', 'Courtland Sutton', 10.9),
    ('Mamby/Tenner', 'Ka''imi Fairbairn', 10.3),
    ('Mamby/Tenner', 'Tony Pollard', 12.8),
    ('Mamby/Tenner', 'Stefon Diggs', 8.6),
    ('Mamby/Tenner', 'Aaron Jones Sr.', 10.5),
    ('Mamby/Tenner', 'RJ Harvey', 8.2),
    ('Mamby/Tenner', 'Mark Andrews', 9.4),
    ('Mamby/Tenner', 'Brian Robinson Jr.', 5.7)
),
resolved as (
  select re.id as roster_entry_id, pd.proj
  from proj_data pd
  join managers m on m.name = pd.manager_name
  join teams t on t.manager_id = m.id
  join seasons s on s.id = t.season_id and s.year = 2026
  join players p on p.name = pd.player_name
  join roster_entries re on re.team_id = t.id and re.player_id = p.id
)
update roster_entries
set stats = coalesce(roster_entries.stats, '{}'::jsonb)
  || jsonb_build_object(
       'proj',
       coalesce(roster_entries.stats -> 'proj', '{}'::jsonb) || jsonb_build_object('1', resolved.proj)
     )
from resolved
where roster_entries.id = resolved.roster_entry_id;
